name: ML CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r lab2/requirements.txt

      - name: Train model
        run: |
          python lab2/src/train.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: lab2/outputs/

  deploy:
    needs: train
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: model-artifacts
          path: lab2/outputs/

      - name: Read metrics
        run: |
          echo "R2=$(jq .r2_score lab2/outputs/results.json)" >> $GITHUB_ENV

      - name: Compare metrics
        run: |
          if (( $(echo "$R2 <= ${{ vars.BEST_R2 }}" | bc -l) )); then
            echo "2022BCD0008 ---- Metric did not improve"
            exit 0
          fi

      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Image
        run: |
          docker build -t hemanth251/wine_predict_2022bcd0008:latest lab2
          docker push hemanth251/wine_predict_2022bcd0008:latest
